### ISSUE TITLE
Audo Update

### ISSUE THREAD

**Issue by ghost** [lsellens/xbmc.addons#7]
Hi lsellens

I am using Audo on v5.0 of OE and now sickrage is giving errors with propers and post processing. I see that you have another bundle here.

What i want to know is if i remove audo where do i get sabnzdb from and will your updated bundle (SickPotatoHead) have sickrage as well ?

If not will audo be updated more often.

Thanks

**Comment by Vodka2014** [comment]
I am going to close this issue as the Auto Update on SickRage works :)
